### ISSUE TITLE
Swagger Editor examples not testable

### ISSUE THREAD

**Issue by Benny-Beermann** [apigee-127/swagger-test-templates#120]
Hi,

I know this is no real concrete issue, but I'm asking myself if I'm doing something wrong. I'm currently investigating the capability of swagger-test-templates, as it looks quite promising and is exactly what we need in our projects. But when I'm generating tests for any of the examples you can load in the Swagger Editor (for example the pretty simple PetStore on Heroku), all the resulting tests are failing afterwards with different validation errors. In this case it looks like, that $ref can't be resolved. Would be nice if someone can help me out.

best regards
Benny

**Comment by noahdietz** [comment]
Benny, hello, in the next release, the `$ref` resolution should be fixed per discussion and related PRs in #104 

We are wrapping things up for the next release.

**Comment by Benny-Beermann** [comment]
Thx for the quick reply Noah. Looking forward to see the next release.
