### ISSUE TITLE
Document return array

### ISSUE THREAD

**Issue by cfjedimaster** [apigee-127/swagger-test-templates#126]
The docs say that the result is an array of file names and test content, but it doesn't document what they actually are, specifically that 'name' is the file name and 'test' is the content.

**Comment by noahdietz** [comment]
Thank you, I'll fix this right away.

**Comment by noahdietz** [comment]
Fixed with commit: [51a5311d554feb4d92f698d5539789b2dbc01b85](https://github.com/apigee-127/swagger-test-templates/commit/51a5311d554feb4d92f698d5539789b2dbc01b85)
