### ISSUE TITLE
Multiple requestData sets don't translate into multiple tests

### ISSUE THREAD

**Issue by jurajpaulo** [apigee-127/swagger-test-templates#128]
Since requestData per requestPath/operation/response is an array, i assumed multiple sets would create multiple tests, one for each set of request data. But only the first one is used.

i.e.

```
requestData: {
  '/albums/{albumId}': {
    get: {
      200: [
        { albumId: 1, description: 'get an album by id 1'},
        { albumId: 3, description: 'get an album by id 3'}
      ]
    }
  }
}
```

creates a test only for `api.get('/albums/1')`, not `api.get('/albums/3')`.

**Comment by Remco75** [comment]
Hmm, I will look into this. I am horribly busy, but will try to find time soon

**Comment by jenkink** [comment]
curious if there has been any movement on this issue? as i too will need to do something like this with my tests

**Comment by noahdietz** [comment]
@jenkink With how closely tied the request data injection/resolution is with the template compilation I think this might be a more involved change to make. Idk when I'll have time to work on it, but I agree that this is a feature we should support
