### ISSUE TITLE
Does this project support YAML?

### ISSUE THREAD

**Issue by baynezy** [apigee-127/swagger-test-templates#134]
I am trying to create tests from a YAML definition.
https://gist.github.com/baynezy/95d9668eaae7a56114609b0b345d52b7

The YAML is valid and if I convert it to JSON then it works as expected.

When it is YAML is appears to be parsing strings as file structure.

**Comment by noahdietz** [comment]
tl;dr No

This module was originally written to be integrated with `swagger-node` and it's CLI, which would take the YAML and resolve all the definitions and present you with a JSON. That's what we built against.

It wouldn't be too hard to add support for this, but it just hasn't been much of an issue for folks, so I hadn't added it.

**Comment by baynezy** [comment]
OK. Shall I raise a proper issue for that then?

**Comment by noahdietz** [comment]
Sure, please do.
