### ISSUE TITLE
Generated tests have broken URLs

### ISSUE THREAD

**Issue by baynezy** [apigee-127/swagger-test-templates#135]
I have a Swagger file

    {
        "swagger": "2.0",
        "info": {
            "title": "The new Uber API",
            "description": "Move your app forward with the Uber API",
            "version": "1.0.0"
        },
        "host": "localhost:8080",
        "schemes": [
            "http"
        ],
        "basePath": "/v1",
        "produces": [
            "application/json"
        ],
        "paths": {
            "/products": {
                "get": {
                    "summary": "Product Types",
                    "description": "The Products endpoint returns information about the Uber products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order.",
                    "parameters": [{
                            "name": "latitude",
                            "in": "query",
                            "description": "Latitude component of location.",
                            "required": true,
                            "type": "number"
                        },
                        {
                            "name": "longitude",
                            "in": "query",
                            "description": "Longitude component of location.",
                            "required": true,
                            "type": "number"
                        }
                    ],
                    "tags": [
                        "Products"
                    ],
                    "responses": {
                        "200": {
                            "description": "An array of products",
                            "schema": {
                                "$ref": "#/definitions/Products"
                            }
                        },
                        "default": {
                            "description": "Unexpected error",
                            "schema": {
                                "$ref": "#/definitions/Error"
                            }
                        }
                    }
                }
            }
        },
        "definitions": {
            "Product": {
                "properties": {
                    "product_id": {
                        "type": "string",
                        "description": "Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles."
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of product."
                    },
                    "display_name": {
                        "type": "string",
                        "description": "Display name of product."
                    },
                    "capacity": {
                        "type": "string",
                        "description": "Capacity of product. For example, 4 people."
                    },
                    "image": {
                        "type": "string",
                        "description": "Image URL representing the product."
                    }
                }
            },
            "Products": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/Product"
                }
            },
            "Error": {
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "fields": {
                        "type": "object"
                    }
                }
            }
        }
    }

That I have generated tests from using this project, and this code:-

    var fs = require("fs"),
        stt = require("swagger-test-templates"),
        swagger = require("../spec/uber.json"),
        config = {
            assertionFormat: "expect",
            testModule: "request",
            pathName: [],
            maxLen: -1
        };

    var tests = stt.testGen(swagger, config);

    tests.forEach(function(element) {
        fs.writeFile("./test/" + element.name, element.test, (err) => {
            if (err) throw err;

            console.log(element.name, " written");
        })
    }, this);

However all the tests fail when run because the URLs generated are not valid.

### Example

    request({
      url: 'http://localhost:8080/\v1\products',
      qs: {
        latitude: 'DATA GOES HERE',longitude: 'DATA GOES HERE'
      },
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    }

What am I doing wrong? Why is it generating URLs this way?

I was expecting it to be `http://localhost:8080/v1/products`

**Comment by noahdietz** [comment]
I'm sorry @baynezy , I could't reproduce the error with the swagger & code you gave me. The paths look as they are expected to.

I'm not sure where to go from here, I'll keep thinking.

**Comment by noahdietz** [comment]
If you're on Windows, this might be the problem

https://github.com/apigee-127/swagger-test-templates/issues/125

**Comment by noahdietz** [comment]
I believe the fix was in release v1.3.0

**Comment by baynezy** [comment]
@noahdietz - that does indeed look like it is resolved and explains why when I check out your project and and run the tests they behave themselves.

However, v1.3.0 was cut on [13th October](https://github.com/apigee-127/swagger-test-templates/releases/tag/v1.3.0) and that fix was in December and [so is not in the NPM package](https://github.com/apigee-127/swagger-test-templates/compare/v1.3.0...master) that I am using.

Any danger of a new release?

**Comment by noahdietz** [comment]
I just published a new release `1.4.0` can you confirm that this behavior is gone? Then close if so.

**Comment by baynezy** [comment]
@noahdietz - that has resolved it thank you.
