### ISSUE TITLE
Schema Validation Always fails

### ISSUE THREAD

**Issue by baynezy** [apigee-127/swagger-test-templates#136]
I have a Swagger file

    {
        "swagger": "2.0",
        "info": {
            "title": "The new Uber API",
            "description": "Move your app forward with the Uber API",
            "version": "1.0.0"
        },
        "host": "localhost:8080",
        "schemes": [
            "http"
        ],
        "basePath": "/v1",
        "produces": [
            "application/json"
        ],
        "paths": {
            "/products": {
                "get": {
                    "summary": "Product Types",
                    "description": "The Products endpoint returns information about the Uber products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order.",
                    "parameters": [{
                            "name": "latitude",
                            "in": "query",
                            "description": "Latitude component of location.",
                            "required": true,
                            "type": "number"
                        },
                        {
                            "name": "longitude",
                            "in": "query",
                            "description": "Longitude component of location.",
                            "required": true,
                            "type": "number"
                        }
                    ],
                    "tags": [
                        "Products"
                    ],
                    "responses": {
                        "200": {
                            "description": "An array of products",
                            "schema": {
                                "$ref": "#/definitions/Products"
                            }
                        },
                        "default": {
                            "description": "Unexpected error",
                            "schema": {
                                "$ref": "#/definitions/Error"
                            }
                        }
                    }
                }
            }
        },
        "definitions": {
            "Product": {
                "properties": {
                    "product_id": {
                        "type": "string",
                        "description": "Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles."
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of product."
                    },
                    "display_name": {
                        "type": "string",
                        "description": "Display name of product."
                    },
                    "capacity": {
                        "type": "string",
                        "description": "Capacity of product. For example, 4 people."
                    },
                    "image": {
                        "type": "string",
                        "description": "Image URL representing the product."
                    }
                }
            },
            "Products": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/Product"
                }
            },
            "Error": {
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "fields": {
                        "type": "object"
                    }
                }
            }
        }
    }

I generate my tests using this code:-

    var fs = require("fs"),
        stt = require("swagger-test-templates"),
        swagger = require("../spec/uber.json"),
        config = {
            assertionFormat: "expect",
            testModule: "request",
            pathName: [],
            maxLen: -1
        };

    var tests = stt.testGen(swagger, config);

    tests.forEach(function(element) {
        fs.writeFile("./test/" + element.name, element.test, (err) => {
            if (err) throw err;

            console.log(element.name, " written");
        })
    }, this);

The generated tests use `z-schema` to validate the response body against the Swagger definitions. However, for me they always fail because the data type returned is a string and the specification is expecting an array.

My API returns the following:

    HTTP/1.1 200 OK
    Server: Apache-Coyote/1.1
    Content-Type: application/json;charset=UTF-8
    Date: Thu, 27 Apr 2017 09:06:26 GMT
    Content-Length: 107
    
    [{"product_id":"cc","description":"Liquid horror","display_name":"Can of Coke","capacity":"10","image":""}]

I have to change the line `expect(validator.validate(body, schema)).to.be.true;` to `expect(validator.validate(JSON.parse(body), schema)).to.be.true;` to make it work.

Am I doing something wrong?

**Comment by noahdietz** [comment]
You aren't doing anything wrong, that would be the fix.

There is some weird behavior, documented/discussed in #94 that kind of explains it. I'm struggling to decide if it should be fixed or not, the issue conversation was non-conclusive.

**Comment by baynezy** [comment]
OK. I will close this ticket and wade in on the other one when I have had a closer look at it.
