### ISSUE TITLE
Is requestData actually implemented?

### ISSUE THREAD

**Issue by baynezy** [apigee-127/swagger-test-templates#137]
I have a Swagger file

    {
        "swagger": "2.0",
        "info": {
            "title": "The new Uber API",
            "description": "Move your app forward with the Uber API",
            "version": "1.0.0"
        },
        "host": "localhost:8080",
        "schemes": [
            "http"
        ],
        "basePath": "/v1",
        "produces": [
            "application/json"
        ],
        "paths": {
            "/products": {
                "get": {
                    "summary": "Product Types",
                    "description": "The Products endpoint returns information about the Uber products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order.",
                    "parameters": [{
                            "name": "latitude",
                            "in": "query",
                            "description": "Latitude component of location.",
                            "required": true,
                            "type": "number"
                        },
                        {
                            "name": "longitude",
                            "in": "query",
                            "description": "Longitude component of location.",
                            "required": true,
                            "type": "number"
                        }
                    ],
                    "tags": [
                        "Products"
                    ],
                    "responses": {
                        "200": {
                            "description": "An array of products",
                            "schema": {
                                "$ref": "#/definitions/Products"
                            }
                        },
                        "default": {
                            "description": "Unexpected error",
                            "schema": {
                                "$ref": "#/definitions/Error"
                            }
                        }
                    }
                }
            }
        },
        "definitions": {
            "Product": {
                "properties": {
                    "product_id": {
                        "type": "string",
                        "description": "Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles."
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of product."
                    },
                    "display_name": {
                        "type": "string",
                        "description": "Display name of product."
                    },
                    "capacity": {
                        "type": "string",
                        "description": "Capacity of product. For example, 4 people."
                    },
                    "image": {
                        "type": "string",
                        "description": "Image URL representing the product."
                    }
                }
            },
            "Products": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/Product"
                }
            },
            "Error": {
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "fields": {
                        "type": "object"
                    }
                }
            }
        }
    }

I have been trying to replace the `'DATA GOES HERE'` placeholders in the generated tests. On reading [the documentation](https://github.com/apigee-127/swagger-test-templates#sending-requestdata) I thought that I could do that by the following:-

    var fs = require("fs"),
        stt = require("swagger-test-templates"),
        swagger = require("../spec/uber.json"),
        config = {
            assertionFormat: "expect",
            testModule: "request",
            pathName: [],
            maxLen: -1,
            requestData: {
                "/products": {
                    get: {
                        200: [{
                            latitude: 10,
                            longitude: 10
                        }]
                    }
                }
            }
        };

    var tests = stt.testGen(swagger, config);

    tests.forEach(function(element) {
        fs.writeFile("./test/" + element.name, element.test, (err) => {
            if (err) throw err;

            console.log(element.name, " written");
        })
    }, this);

However, that made zero difference to the generated tests. So I started reading through the code and I cannot find any reference to the `requestData` property anywhere but the documentation. Am I badly missing something?

**Comment by baynezy** [comment]
Ok,
So on further investigation I can see it has been implemented for [request bodies](https://github.com/apigee-127/swagger-test-templates/blob/master/test/request-data/test.js#L46-L52).

However, [the documentation](https://github.com/apigee-127/swagger-test-templates#sending-requestdata) seems to indicate that it is possible to set the query parameter values as well.

**Comment by noahdietz** [comment]
You are right, the docs do indicate this should be possible when in how it says `valid path or query parameters` but it is not implemented in the templates, at first glance.

**Comment by baynezy** [comment]
Thanks. I will have a go at implementing this.
