### ISSUE TITLE
Add YAML Support

### ISSUE THREAD

**Issue by baynezy** [apigee-127/swagger-test-templates#138]
Currently the project does not work with a Swagger spec written in YAML. YAML is a Superset of JSON so this could be achieved by doing a conversion beforehand.

**Comment by Conorrr** [comment]
You can use [yamljs](https://www.npmjs.com/package/yamljs) to load yaml files. I suspect external $ref dependencies will not resolve though.

**Comment by noahdietz** [comment]
If the `$ref` are in left intact, thats fine, the JSON spec should be run through `deref` anyways.

**Comment by Conorrr** [comment]
Refs to internal elements will be fine, but the reffed external files will be in yaml. Does deref support yaml files?

**Comment by noahdietz** [comment]
Good point, no [json-schema-deref-sync](https://www.npmjs.com/package/json-schema-deref-sync) doesn't support yaml files...those would all have to be converted prior to `deref` running on the main spec file. hm...

**Comment by baynezy** [comment]
Sounds like converting YAML Swagger to JSON Swagger is a whole project in it's own right.

**Comment by baynezy** [comment]
Or effectively a YAML version of [json-schema-deref-sync](https://www.npmjs.com/package/json-schema-deref-sync).

**Comment by noahdietz** [comment]
Yeah, so yaml<>json conversion might be too much. 

Projects like [sway](github.com/apigee-127/sway) accomplish this, but it would require a significant rewrite of this module's execution path. I'm giving it a shot in another, unofficial project called [oatts](github.com/noahdietz/oatts).

Can we agree on closing this issue as the work might be out of the scope of this project?

**Comment by baynezy** [comment]
Closing as out of scope
