### ISSUE TITLE
Update handlebars to the latest version

### ISSUE THREAD

**Issue by demns** [apigee-127/swagger-test-templates#144]
As it was stated here: 
https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v405---november-19th-2015
Uglify until 2.6 contained security vulnerability, more info here: https://nodesecurity.io/advisories/48

Is it possible to update handlebars version to the latest one? Thanks!

*nsp check currently returns this: 
![selection_029](https://cloud.githubusercontent.com/assets/7815691/26056139/ac305ec6-397c-11e7-97f5-dae78145c415.png)
and some extra

**Comment by noahdietz** [comment]
Thanks @demns for opening this.

I just tried things out locally and updating the package breaks the tests. As such, it will take some more time to get this change in. The test comparison files need to be updated.

Just wanted to give you an ack.

**Comment by noahdietz** [comment]
Turns out it was an easier fix than I thought. Through looking at the change logs and the test diffs, I was able to narrow it down to the breaking change.

Interesting discussion about behavior of [contexts in handlebars](https://github.com/wycats/handlebars.js/issues/1028)

**Comment by demns** [comment]
@noahdietz thank you very much for your investigation and an extremely quick fix! Keep it up!
