### ISSUE TITLE
HTTPS API

### ISSUE THREAD

**Issue by NeverZong** [apigee-127/swagger-test-templates#149]
Hello, i wanna know if this tool supports https request?

**Comment by baynezy** [comment]
@NeverZong - yes it does. It respects the `schemes` node of [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object)

So if you define your API to be on `https` then this project will generate tests that make calls to it there.

**Comment by NeverZong** [comment]
When I use https to generate the tests , the tests  runs the error, seems like the request was not sent to the background. Is there any demo of https can refer to.

**Comment by NeverZong** [comment]
Is this tool used for black box testing or white box testing? Looking forward to your reply, thank you.

**Comment by baynezy** [comment]
@NeverZong - It creates Mocha tests that can be executed against your running API. So it is for black box testing.

Regarding you error can you post an example of your problem? There is nothing special about testing HTTPs, the tests just get generated on a different protocol.

**Comment by NeverZong** [comment]
@baynezy - First thank you for your help.
Every test error is:

```
TypeError: Cannot read property 'status' of undefined
      at Test._assertStatus (node_modules\supertest\lib\test.js:263:10)
      at Test._assertFunction (node_modules\supertest\lib\test.js:281:11)
      at Test.assert (node_modules\supertest\lib\test.js:171:18)
      at assert (node_modules\supertest\lib\test.js:131:12)
      at node_modules\supertest\lib\test.js:128:5
      at Test.Request.callback (node_modules\superagent\lib\node\index.js:699:3)
      at ClientRequest.<anonymous> (node_modules\superagent\lib\node\index.js:636:10)
      at TLSSocket.socketErrorListener (_http_client.js:310:9)
      at emitErrorNT (net.js:1276:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

It looks like all `res `is undefined. An example of tests is:
 ```
customFormats(ZSchema);

var validator = new ZSchema({});
var supertest = require('supertest');
var api = supertest('https://10.40.44.73:16843'); // supertest init;
var expect = chai.expect;

describe('/v1.0/{project_id}/quotas', function() {
  describe('put', function() {
    it('should respond with 200 OK and fewrf', function(done) {
      api.put('/v1.0/087090c648064e0a8d8c243780ad91bf/quotas')
      .set('Content-Type', 'application/json')
      .send({
              "quotas":
                  {
                      "resources":
                          [{
                              "type": "platform_quantity",
                              "quota": "4"
                          }]
                  }
          }
      )
      .expect(200)
      .end(function(err, res) {
        if (err) return done(err);

        console.log(res.body);
        expect(res.body).to.equal(null); // non-json response or no schema
        done();
      });
    });
  });
});

```

**Comment by NeverZong** [comment]
When the Argument `testModule` uses `request`, the error will be:
```
1) /v1.0/{project_id}/quotas get should respond with 200 OK:
     Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND w00417565 w00417565:80
      at ClientRequest.onError (node_modules\tunnel-agent\index.js:177:17)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at connectErrorNT (net.js:1020:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by baynezy** [comment]
If you look at the generated test the URI it is trying to call is `/v1.0/087090c648064e0a8d8c243780ad91bf/quotas`

Which has no protocol or domain. Are you setting a `host` in your swagger file?

**Comment by NeverZong** [comment]
Yes, I set a `host `in my swagger file.
```
"host": "10.40.44.73:8090",
"schemes": ["https"] ,
```
When the Argument `testModule `uses `supertest`, 
`var api = supertest('https://10.40.44.73:16843'); // supertest init;`
` api.put('/v1.0/087090c648064e0a8d8c243780ad91bf/quotas')`
the error is:
`TypeError: Cannot read property 'status' of undefined`

When the Argument `testModule `uses `request`, the tset is 
```
it('should respond with 200 OK and fewrf', function(done) {
      request({
        url: 'https://10.40.44.73:16843/v1.0/087090c648064e0a8d8c243780ad91bf/quotas',
        json: true,
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json'
        },
        body: {"quotas":{"resources":[{"type":"platform_quantity","quota":"2"}]}}
      },
      function(error, res, body) {
        if (error) return done(error);

        expect(res.statusCode).to.equal(200);

        expect(body).to.equal(null); // non-json response or no schema
        done();
      });
    });
```
the error is:
`Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND w00417565 w00417565:80`

**Comment by baynezy** [comment]
@NeverZong - are you behind a proxy by any chance?

https://stackoverflow.com/a/33892578/1003830

**Comment by NeverZong** [comment]
@baynezy Yes,you are right！I finally reloaded `Node `to solve this problem. Thank you!

I have another problem here. My API only returns the http state code 200. The generated test's assertion is: 
```
expect(res.statusCode).to.equal(200);
 expect(body).to.equal(null); // non-json response or no schema
```
and the error is:
`Uncaught AssertionError: expected undefined to equal null`

I need to manually modify the code as follows
```
expect(res.statusCode).to.equal(200);
 expect(body).to.equal(undefined); // non-json response or no schema
```
How to fix this?
Is my `json `file written wrong? My background interface is implemented in `Java`.Thank you very much for your help！

**Comment by baynezy** [comment]
@NeverZong - can you open a new issue for this? As we have resolved this one. In that issue can you post the Swagger file so I can see what you have put in there?

**Comment by baynezy** [comment]
@noahdietz - this should be closed.

**Comment by noahdietz** [comment]
@baynezy thank you for working through this.
