### ISSUE TITLE
Path parameter definitions are mistaken as operations, need to be ignored

### ISSUE THREAD

**Issue by noahdietz** [apigee-127/swagger-test-templates#15]
```json
"/geographies/{geo-id}/media/recent": {
            "parameters": [
                {
                    "name": "geo-id",
                    "in": "path",
                    "description": "Geolocation ID",
                    "type": "integer"
                }
            ],
```

**Comment by mohsen1** [comment]
There is also vendor extensions. Possible operation names are a fixed set. So:

* in each iteration make sure you're ignoring vendor extensions. e.g. `x-apigee-...`
* when iterating in path for operation, filter down the keys to predefined list of valid operation. Can be found in #7
