### ISSUE TITLE
Re-generate tests not overwriting changes

### ISSUE THREAD

**Issue by lcofre** [apigee-127/swagger-test-templates#152]
Thanks for this project!

Following your advice @baynezy in issue #148 I could generate the tests and run them with mocha.

Now my doubt is, How can I customize the tests (e.g. 'DATA GOES HERE' and 'PARAM GOES HERE' appear when parameters are defined in body and path, respectively) but allow to re-generate them when the API definition changes?

For query parameters I see a .env file that contains the variables I need to change.

Thanks in advance for your help!

**Comment by baynezy** [comment]
@lcofre take a look at [requestData](https://github.com/apigee-127/swagger-test-templates/blob/master/README.md#sending-requestdata) parameter

**Comment by lcofre** [comment]
Thanks very much! I configured the the tests through the requestData parameter.

Sorry for a question so easily answerable by reading the readme.

Thanks!

**Comment by baynezy** [comment]
@lcofre - no problem. That is the world telling us that we should have better documentation :smile:
