### ISSUE TITLE
Test Execution Order

### ISSUE THREAD

**Issue by jenkink** [apigee-127/swagger-test-templates#157]
This is more of a question than an issue, but is there a way to customize the order in which the tests are generated, say if i wanted to do a PUT, POST, GET, DELETE? Or would that be dependent on how the are ordered in the swagger file?

**Comment by noahdietz** [comment]
No there isn't a way to customize the order of the operations as they are generated. But yes your suggestion about op order in your spec is correct. The tests are generated sequentially/as they appear in the spec.

Please close this if the answer is sufficient! :)

**Comment by jenkink** [comment]
ok great thanks closing.
