### ISSUE TITLE
Test Templates for rspec Added

### ISSUE THREAD

**Issue by HarishRaj11** [apigee-127/swagger-test-templates#182]
The test templates for Rspec has been created and which can be accessed by setting the lang attribute of the config variable to rb. The value of the lang variable has been defaulted to js (pointing to javascript folder). Can u check if the templates are fine and approve the PR as Rspecs are vital in companies. Thanks

**Comment by noahdietz** [comment]
I would prefer that this project stick to generating strictly Node.js code. Other Node.js request/testing frameworks are acceptable. Maintaining multiple language targets adds more complexity than I'd like. I appreciate the desire to contribute the rspec work you've done back to the project.
