### ISSUE TITLE
Resolve references before processing the Swagger

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-test-templates#25]
Use [this module](https://github.com/whitlockjc/json-refs) to resolve all `$ref`s before using the Swagger specs

**Comment by mohsen1** [comment]
@elsapeng the resolving should happen in Swagger Node land.

**Comment by noahdietz** [comment]
Fix [here](https://github.com/apigee-127/swagger-node/commit/144c3e1dd10237365d361f5e792184e30a45557f)
