### ISSUE TITLE
overwriting prompt appears twice for the same file

### ISSUE THREAD

**Issue by noahdietz** [apigee-127/swagger-test-templates#53]
When running ```swagger project generate-test``` again after having already generated tests, i expected to get the overwrite prompt once for each file, but instead I get it twice for each. Still able to answer and see the options, it just appears twice. 

Happens on both petstore-full and Instagram APIs

**Comment by elsapeng** [comment]
fixed by [issue](https://github.com/apigee-127/swagger-node/commit/0d64dfc56c5431264779e2ddece324575de0e8c2)
