### ISSUE TITLE
--force option not recognized at cli

### ISSUE THREAD

**Issue by noahdietz** [apigee-127/swagger-test-templates#54]
Neither ```-o``` nor ```--force``` are recognized as CLI options for ```swagger project generate-test```, but the rest of the overwriting functionality is there and working.

**Comment by elsapeng** [comment]
@noahdietz, a quick question, so when you do generate-test -o, do you need to add anything after that, I mean like generate-test -o true, or something?

**Comment by noahdietz** [comment]
@elsapeng no, the existence of the option in the CLI should indicate ```true``` and the absence should make the flag ```false``` by default
