### ISSUE TITLE
error on default project using should

### ISSUE THREAD

**Issue by theganyo** [apigee-127/swagger-test-templates#64]
```
$ swagger project create test-test -f connect
$ cd test-test
$ swagger project generate-test -t should
$ swagger project test
Running tests in: /Users/sganyo/temp/test-test/test...
[SyntaxError: /Users/sganyo/temp/test-test/test/api/client/hello-test.js:53
      .expect(default)
              ^^^^^^^
Unexpected token default]
```

**Comment by noahdietz** [comment]
@elsapeng and i talked about this a while ago and we weren't sure how to determine what the default response code should be.

Maybe we shouldn't include that assertion at all if it is the ```default``` response case?

**Comment by noahdietz** [comment]
@elsapeng is replacing with a string indicating a status code must be entered, just to make it valid JavaScript
