### ISSUE TITLE
add ability to generate load tests at operation level

### ISSUE THREAD

**Issue by noahdietz** [apigee-127/swagger-test-templates#76]
It would be nice to have the ability to load test an API on an operation by operation basis.

Possible module for generated load tests could be based on [arete](https://www.npmjs.com/package/arete), which interfaces well with Mocha out of the box.

But what would be the best way to expose this functionality? Through command line flag that indicates the existence of a file with a list of paths + operations? Specifying on an individual basis through CLI is too cumbersome IMO.

**Comment by elsapeng** [comment]
I think if the user wants to load test, he/she has to specify which path and which operation, we can provide the list, but what if the list is too long? That might look strange in CLI

**Comment by noahdietz** [comment]
I agree, using a CLI would be too much, which is why I think they should specify the path + operation list in a file as a JSON object that will make it easy to access in testGeneration

**Comment by mohsen1** [comment]
This module doesn't have a CLI so we don't worry how the CLI will look like in swagger-node. In it's own API however we can introduce a new option to enable load testing for the paths. We can even break the API by bumping version to `2.0`

Without breaking the API
```js
var testGen = require('swagger-test-templates');
var swagger = require('/path/to/swagger.json');
var config = {
  assertionFormat: 'should',
  testModule:'supertest',
  pathNames:['/user', '/user/{id}'],
  loadTest: [{pathName: '/user', load: {requests: 10e3, concurrent: 100}]
};

// Generates an array of JavaScript test files following specified configuration
testGen(swagger, config);
```

New API

```js
var testGen = require('swagger-test-templates');
var swagger = require('/path/to/swagger.json');
var config = {
  assertionFormat: 'should',
  testModule:'supertest',
  paths:[{pathName: '/user', load: { /* ... */ }, {pathName: '/user/{id}'}]
};

// Generates an array of JavaScript test files following specified configuration
testGen(swagger, config);
```

**Comment by elsapeng** [comment]
I can work on this rn, and also i found [this](https://www.npmjs.com/package/loadtest) looks helpful....

**Comment by noahdietz** [comment]
@elsapeng i think the module i linked in my original post might be better, as it interfaces with mocha without any extra work, found [here](https://www.npmjs.com/package/arete)

**Comment by elsapeng** [comment]
got it, so i think the api would look like:

```js
var testGen = require('swagger-test-templates');
var swagger = require('/path/to/swagger.json');
var config = {
  assertionFormat: 'should',
  testModule:'supertest',
  pathNames:['/user', '/user/{id}'],
  loadTest: [{pathName: '/user', operation: 'get', load: {requests: 10e3, concurrent: 100}]
};

// Generates an array of JavaScript test files following specified configuration
testGen(swagger, config);
```

**Comment by mohsen1** [comment]
I like this API @elsapeng +1 from me!

**Comment by noahdietz** [comment]
Do we considering incorporating this into swagger-node CLI? If so, should the discussion be held here or in a new issue in a-127/swagger-node?

**Comment by mohsen1** [comment]
I would make a PR directly to swagger-api/swagger-node and ask @theganyo about CLI arguments design

**Comment by noahdietz** [comment]
PR for CLI development [opened](https://github.com/swagger-api/swagger-node/pull/274). Closing this issue.
