### ISSUE TITLE
Changes in Readme

### ISSUE THREAD

**Issue by elsapeng** [apigee-127/swagger-test-templates#77]
Do we need to add some explanation to the readme? :
- the pathname, if provided an empty array, it will generate tests for all paths
- we also have maxlen in config, so the templates have the max length limits
- pathname, testmodule, assertionformat are required, the maxlen & future config(like load test) are optional

**Comment by mohsen1** [comment]
From what I remember I wrote skeleton of the doc. Please push fixes (I know I have tons of type all the time! :D) to the branch I made PR from
