### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by elsapeng** [apigee-127/swagger-test-templates#81]
@mohsen1 
Should we release our next version rn as v1.2.0 ? and it seems we kind of skipped our v1.1.1 (we made some small changes but not published)

**Comment by elsapeng** [comment]
Ok, based on what we've talked on hipchat, we have some more questions and look forward to your comments and advice @mohsen1 @theganyo: 
First is how to incorporate load testing in swagger-node cli?
And also, if we want to add controller generator, what we can do for the users? Right now what we can think of is to add stubs and also validate the requests (like parameters), but maybe there is more we can do.
Also, how to reflect the controller generation in swagger-node cli, should it be just another command line like '''swagger project generate-controller''', or we should have only one command, like '''swagger project generate''', and make testing generation, controller generation as options, but then we have options of test options....I am not sure which way is better...

**Comment by noahdietz** [comment]
@mohsen1 we talked through an extension/pivot for swagger-test-templates in hip chat if you want to see the conversation.

Like linjie said, we want to generate controller code that does minimal validation of request parameters to determine the proper response. This is like a mock controller, considering we can't wire to a database

**Comment by mohsen1** [comment]
I don't have access to Hipchat. Do you mean generating swagger-node controllers? Shouldn't that be part of swagger-node itself?

**Comment by noahdietz** [comment]
That's a good point. Does it make sense to rewrite a lot of the same code that parses the swagger for path/operation information, though? Could we not pivot this module to generate controller code as well?

Or should we make another module that would be a dependency for swagger-node 'swagger-controllers' or something?

**Comment by noahdietz** [comment]
Also, the controllers aren't limited to use in swagger-node, although they are NodeJS specific, so it might be nice to have it modularized out of swagger-node.

**Comment by mohsen1** [comment]
Can you give me an example of simple Swagger and generated controller? Isn't a controller just an empty function with `req, res, next` arguments? If there isn't much code inside of the controller and all we need is generating placeholder files it should happen in swagger-node then.

**Comment by noahdietz** [comment]
```yaml
  /:
    get:
      parameters:
        - name: id
          description: ID of object
          in: query
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: BAD
```

Based on the API above, we could generate a controller that provided a minimal response based on request parameter validation.

```js
function getByID(req, res) {
  var id = req.swagger.params.id.value;

  if (id !== undefined) { // validate request based on API, should use z-schema on big request objects
    res.send(200);
  } else {
    res.send(400)
  }
}
```
This could be a pretty useful start to developing the controller logic, followed by wiring up a database. On more complex request parameters, there could be z-schema validation to ensure its a valid request.

The tricky part is when we have more complex responses, but since we have the response schema in the swagger, we can set up a skeleton response that just indicates to the developer what needs to be returned.
