### ISSUE TITLE
Readme needs to be updated, Sample code gives an error..

### ISSUE THREAD

**Issue by anil614sagar** [apigee-127/swagger-test-templates#82]
testGen(swagger, config);
^
TypeError: object is not a function

Ideally readme last line should be

testGen.testGen(swagger, config);

**Comment by mohsen1** [comment]
You're right. the [export](https://github.com/apigee-127/swagger-test-templates/blob/master/index.js#L500) has changed. Could you make a PR to fix this?

**Comment by noahdietz** [comment]
fixed with #83
