### ISSUE TITLE
Supply default path parameters (replace where PARAM GOES HERE)

### ISSUE THREAD

**Issue by mm-gmbd** [apigee-127/swagger-test-templates#90]
First, thanks for swagger-test-templates -- this looks like the start of a great tool (and a good start at that)!

I have a use case where almost all paths in the API contain a path parameter. It would be a great feature to be able to supply an object, say `pathParams`, where, if the parameter name enclosed in curly braces in the path matched a key in `pathParams`, it would be replaced with the corresponding value rather than just `{paramName PARAM GOES HERE}`.

Thoughts on this? Thanks again!
-Max

**Comment by noahdietz** [comment]
Fixed with #91
